# Generated by Django 3.0.5 on 2020-08-21 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0002_auto_20200819_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Данные браузера',
                'verbose_name_plural': 'Данные браузера',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Ключ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Токен',
                'verbose_name_plural': 'Токены',
            },
        ),
        migrations.CreateModel(
            name='LoginTry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Успешен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('browser_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.BrowserData', verbose_name='Браузер')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка входа',
                'verbose_name_plural': 'Попытки входов',
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='browserdata',
            name='accept_encoding_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encodings', to='user_app.Value', verbose_name='HTTP_ACCEPT_ENCODING'),
        ),
        migrations.AddField(
            model_name='browserdata',
            name='accept_lang_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langs', to='user_app.Value', verbose_name='HTTP_ACCEPT_LANGUAGE'),
        ),
        migrations.AddField(
            model_name='browserdata',
            name='guid_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guids', to='user_app.Value', verbose_name='GUID'),
        ),
        migrations.AddField(
            model_name='browserdata',
            name='http_accept_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepts', to='user_app.Value', verbose_name='HTTP_ACCEPT'),
        ),
        migrations.AddField(
            model_name='browserdata',
            name='luid_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='luids', to='user_app.Value', verbose_name='LUID'),
        ),
        migrations.AddField(
            model_name='browserdata',
            name='remote_addr_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remotes', to='user_app.Value', verbose_name='REMOTE_ADDR'),
        ),
        migrations.AddField(
            model_name='browserdata',
            name='user_agent_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='user_app.Value', verbose_name='HTTP_USER_AGENT'),
        ),
        migrations.AddField(
            model_name='browserdata',
            name='x_forwarded_val',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='user_app.Value', verbose_name='HTTP_X_FORWARDED_FOR'),
        ),
    ]
