# Generated by Django 3.1 on 2020-08-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20200821_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locale',
            field=models.TextField(default='ru-RU', verbose_name='Язвк'),
        ),
    ]
