# Generated by Django 3.1 on 2020-08-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_profile_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='locale',
            field=models.TextField(default='ru-RU', verbose_name='Язык'),
        ),
        migrations.DeleteModel(
            name='LoginTry',
        ),
    ]
