# Generated by Django 3.1 on 2020-08-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_logic', '0004_remove_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.TextField(default='income', verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
