# Generated by Django 3.1 on 2020-08-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_logic', '0005_record_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.TextField(default='income', verbose_name='Тип'),
        ),
    ]
